- hosts: all
  vars:
    version_docker: "17.12.0~ce-0~debian"
    version_kubernetes: "1.8.9"
  roles:
    - common
    - kubeadm

- hosts: master
  roles:
    - master
    - dashboard

- hosts: all:!master
  roles:
    - workers