# playbook to upgrade cluster to latest available version

- hosts: master
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes

    - name: Upgrade kubeadm
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - kubeadm={{ version_kubernetes }}-00

    # - name: Determine latest stable version of Kubernetes
    #   shell: curl -sSL https://dl.k8s.io/release/stable.txt
    #   register: stable_ver

    - name: Upgrade cluster with kubeadm
      shell: "kubeadm upgrade apply -y v{{ version_kube_cluster }}"
      async: 300
      poll: 5

    - name: Cordon Hosts
      shell: "kubectl cordon {{ item }}"
      with_items:
        - "{{ groups['all'] }}"
      tags: cordon

    - name: Drain Hosts
      shell: "kubectl drain {{ item }} --ignore-daemonsets"
      with_items:
        - "{{ groups['all'] }}"
      ignore_errors: yes
      tags: drain

- hosts: all
  tasks:
    - name: Upgrade Y'all
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet={{ version_kubernetes }}-00
        - kubectl={{ version_kubernetes }}-00
      tags:
        - kubelet
        - kubectl

- hosts: master
  tasks:
    - name: Uncordon Hosts
      shell: "kubectl uncordon {{ item }}"
      with_items:
        - "{{ groups['all'] }}"
      tags: uncordon