# playbook to change hostnames to values in inventory file

- hosts: all
  sudo: yes
  tasks:

    - name: main | changing hostname to match inventory_hostname
      hostname:
        name: "{{ inventory_hostname }}"
      register: "hostname_status"
      become: true
      when: ansible_hostname != inventory_hostname

    - name: main | restarting machine
      shell: sleep 2 && shutdown -r now "rebooting to complete hostname change"
      async: 1
      poll: 0
      ignore_errors: true
      become: true

    - name: main | waiting for server to come back
      wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: 22
        search_regex: OpenSSH
        delay: 10
      vars:
        ansible_connection: local
      become: false
