---
# tasks file for kubeadm

# https://gist.github.com/alexellis/fdbc90de7691a1b9edb545c17da2d975
- name: Disable Swap
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove

- name: Determine if Kubernetes is installed
  stat:
    path: /usr/bin/kubeadm
  register: kube_there
  ignore_errors: True

- name: Reset Kubernetes if installed
  shell: kubeadm reset
  register: kubeadm_reset
  when: kube_there.stat.exists == True

- name: Remove any old versions of Kubernetes
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  when: kube_there.stat.exists == True

# Docker Convenience Script Can Only Be Run Once
- name: Determine if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_there
  ignore_errors: True

- name: Remove any old versions of docker
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - docker
    - docker-engine
    - docker.io
    - docker-ce
  when: docker_there.stat.exists == True

# https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository
# https://kubernetes.io/docs/setup/independent/install-kubeadm/
- name: Install Docker requirements
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    update_cache: yes
    # filename: 'docker'

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

# https://docs.docker.com/install/linux/docker-ce/debian/#install-docker-ce-1
- name: Install Docker
  apt:
    update_cache: yes
    name: docker-ce={{ version_docker }}
    state: installed

- name: Add Google Cloud Repo Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main"
    state: present
    filename: 'kubernetes'

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install k8s Y'all
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: installed
  with_items:
    - kubelet={{ version_kubernetes }}
    - kubeadm={{ version_kubernetes }}
    - kubectl={{ version_kubernetes }}