---
# tasks file for kubeadm

# https://gist.github.com/alexellis/fdbc90de7691a1b9edb545c17da2d975
- name: Disable Swap
  shell: dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove

- name: Determine if Kubernetes is installed
  stat:
    path: /usr/bin/kubeadm
  register: kube_there
  ignore_errors: True

- name: Reset Kubernetes if installed
  shell: kubeadm reset
  register: kubeadm_reset
  when: kube_there.stat.exists == True

- name: Remove any old versions of Kubernetes
  apt:
    name: {{ item }}
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    state: absent
  when: docker_there.stat.exists == True

# Docker Convenience Script Can Only Be Run Once
- name: Determine if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_there
  ignore_errors: True

- name: Remove any old versions of docker
  apt:
    name: {{ item }}
  with_items:
    - docker
    - docker-engine
    - docker.io
    - docker-ce
    state: absent
  when: docker_there.stat.exists == True

# https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script
# - name: Run Docker Install Script
#   script: files/get-docker.sh
#   when: docker_there.stat.exists == False

# https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script
- name: Run Docker Install Script online
  shell: wget -qO- https://get.docker.com/ | sed 's/docker-ce/docker-ce={{ version_docker }}' | sh
  when: docker_there.stat.exists == False

# https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository
# - name: Install Docker requirements
#   apt:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - apt-transport-https
#     - ca-certificates
#     - curl
#     - gnupg2
#     - software-properties-common
#   when: docker_there.stat.exists == False

# https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository
# - name: Add Docker official GPG Key
#   shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

# https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository
# - name: Add Docker to Stable Repo
#   shell: echo "deb [arch=armhf] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
#   when: docker_there.stat.exists == False

# - name: apt-get update
#   apt:
#     update_cache=yes
#     autoclean=yes
#     autoremove=yes
#     cache_valid_time=86400
#   when: docker_there.stat.exists == False

# https://docs.docker.com/install/linux/docker-ce/debian/#install-docker-ce-1
# - name: Install Docker from apt
#   apt:
#     name: "{{ item }}"
#     state: {{ version_docker }}
#   with_items:
#     - docker-ce
#   when: docker_there.stat.exists == False

# https://kubernetes.io/docs/setup/independent/install-kubeadm/
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: Add Google Cloud Repo Key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

- name: Add Kubernetes to Available apt Sources
  template:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: 0644

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install k8s Y'all
  apt:
    name: "{{ item }}"
    state: {{ version_kubernetes }}
  with_items:
    - kubelet
    - kubeadm
    - kubectl