---
# tasks file for common
- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: config
  tags:
    - boot
  retries: 5

- name: Setting config options at boot
  copy:
    src: config.txt
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0755
  register: config
  tags:
    - boot
  retries: 5

# # Run once because it fails always first time
# - name: Pass bridged IPv4 traffic to iptables' chains [test]
#   sysctl:
#     name: net.bridge.bridge-nf-call-iptables
#     value: 1
#     state: present
#   ignore_errors: yes

# # Run for reals
# - name: Pass bridged IPv4 traffic to iptables' chains [for reals]
#   sysctl:
#     name: net.bridge.bridge-nf-call-iptables
#     value: 1
#     state: present
#   retries: 5

- name: apt-get update
  apt:
    # update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400
    purge: yes

- name: apt-get upgrade
  apt:
    upgrade: full
    force: yes
  retries: 5

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot for /boot/config.txt Change"
  async: 1
  poll: 0
  ignore_errors: True
  when: config|changed
  tags:
    - boot
    - shutdown

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 15
    timeout: 90
  become: False
  when: config|changed
  tags:
    - boot
    - shutdown
  retries: 5