---
# tasks file for master
- name: Reset Kubernetes Master
  shell: kubeadm reset
  register: kubeadm_reset

- name: Initialize Master
  shell: kubeadm init --token={{ token }} --apiserver-advertise-address={{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }} --kubernetes-version=v{{ version_kubernetes }} --pod-network-cidr={{ podnet }}
  register: kubeadm_init
  when: kubeadm_reset|succeeded

- name: Create kubeconfig directory
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy kubeconfig to /root/.kube/ directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  when: kubeadm_init

- name: Fetch kubeconfig file to local .kube/ directory
  fetch:
    # src: /root/.kube/config
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: yes

- name: Join Kubernetes Cluster
  shell: kubeadm join --token={{ token }} --discovery-token-unsafe-skip-ca-verification --ignore-preflight-errors=all {{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}:6443
  when: kubeadm_reset|succeeded
  register: kubeadm_join

- name: Install Weave (Networking)
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" 
  when: cni_net == "weave"

- name: Install Weave Custom (Networking)
  shell: curl -sSL "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" | sed "s/weave-kube/weave-kube-arm/g" | kubectl apply -f -
  when: cni_net == "weave_kube_arm"

- name: Install Flannel (Networking)
  shell: curl -sSL "https://rawgit.com/coreos/flannel/v{{ version_flannel }}/Documentation/kube-flannel.yml" | sed "s/amd64/arm/g" | kubectl create -f -
  when: cni_net == "flannel"

- name: Poke kubelet
  systemd:
    name: kubelet.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke

- name: wait 30 seconds for Networking to settle
  wait_for:
    delay: 30
