---
# tasks file for master
- name: Reset Kubernetes Master | kube 1.11.x
  shell: kubeadm reset --force
  register: kubeadm_reset
  when:
    - version_kubernetes.find('1.11.') != -1

- name: Reset Kubernetes Master | kube 1.10.x 1.9.x
  shell: kubeadm reset
  register: kubeadm_reset
  when:
    - version_kubernetes.find('1.10.') != -1 or version_kubernetes.find('1.9.') != -1

- name: Initialize Master | weave+kube 1.11.x
  shell: kubeadm init --token={{ token }} --apiserver-advertise-address={{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }} --kubernetes-version=v{{ version_kube_cluster }} --pod-network-cidr={{ podnet }} --ignore-preflight-errors=all
  register: kubeadm_init
  when:
    - kubeadm_reset is succeeded
    - cni_net == "weave"
    - version_kubernetes.find('1.11.') != -1

- name: Initialize Master | weave+kube 1.10.x
  shell: kubeadm init --token={{ token }} --apiserver-advertise-address={{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }} --kubernetes-version=v{{ version_kube_cluster }} --pod-network-cidr={{ podnet }}
  register: kubeadm_init
  when:
    - kubeadm_reset is succeeded
    - cni_net == "weave"
    - version_kubernetes.find('1.10.') != -1

# kubeadm bug "/var/run/dockershim.sock" error in 1.9.x https://github.com/kubernetes/kubeadm/issues/733
- name: Initialize Master | weave+kube 1.9.x
  shell: kubeadm init --token={{ token }} --apiserver-advertise-address={{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }} --kubernetes-version=v{{ version_kube_cluster }} --pod-network-cidr={{ podnet }} --ignore-preflight-errors=cri
  register: kubeadm_init
  when:
    - kubeadm_reset is succeeded
    - cni_net == "weave"
    - version_kubernetes.find('1.9.') != -1

- name: Print kubeadm init response
  debug:
    var: kubeadm_init
    verbosity: 0

- name: Initialize Master | flannel+kube 
  shell: kubeadm init --token={{ token }} --apiserver-advertise-address={{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }} --kubernetes-version=v{{ version_kube_cluster }} --pod-network-cidr={{ podnet }}
  register: kubeadm_init
  when:
    - kubeadm_reset is succeeded
    - cni_net == "flannel"

- name: Create kubeconfig directory
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy kubeconfig to /root/.kube/ directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    backup: yes
  when: kubeadm_init

- name: Fetch kubeconfig file to local-clone .config/ directory
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: .config/kubeconfig
    flat: yes

- name: Backup local kubeconfig to ~/.kube/config.rak8s_backup.DATETIME
  shell: cp ~/.kube/config ~/.kube/"config.rak8s_backup.$(date +"%Y%m%d_%H%M%S")"

- name: Fetch kubeconfig file to local ~/.kube/ directory
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: yes

- name: Join Kubernetes Cluster | kube 1.11.x 1.10.x 1.9.x
  shell: kubeadm join --token={{ token }} --discovery-token-unsafe-skip-ca-verification --ignore-preflight-errors=all {{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}:6443
  when:
    - kubeadm_reset is succeeded
    - version_kubernetes.find('1.11.') != -1 or version_kubernetes.find('1.10.') != -1 or version_kubernetes.find('1.9.') != -1
  register: kubeadm_join

- name: Install CNI Networking | weave
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" 
  when: cni_net == "weave"

- name: Install CNI Networking | flannel
  shell: curl -sSL "https://rawgit.com/coreos/flannel/v{{ version_flannel }}/Documentation/kube-flannel.yml" | sed "s/amd64/arm/g" | kubectl create -f -
  when: cni_net == "flannel"

- name: Poke kubelet 2
  systemd:
    name: kubelet.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke

- name: wait 30 seconds for Networking to settle
  wait_for:
    delay: 30
